/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CapoeiraViewer: typeof import('./components/CapoeiraViewer.vue')['default']
    CapoeiraViewerBackUp: typeof import('./components/CapoeiraViewerBackUp.vue')['default']
    Chatbotpage: typeof import('./components/chatbotpage.vue')['default']
    ChatBubble: typeof import('./components/ChatBubble.vue')['default']
    ChatHeader: typeof import('./components/ChatHeader.vue')['default']
    ChatInput: typeof import('./components/ChatInput.vue')['default']
    copy: typeof import('./components/CapoeiraViewerBackUp.vue')['default']
    FilterTabs: typeof import('./components/FilterTabs.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HeroSection: typeof import('./components/HeroSection.vue')['default']
    MediaControls: typeof import('./components/MediaControls.vue')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    ParentBenefits: typeof import('./components/ParentBenefits.vue')['default']
    ProductTile: typeof import('./components/ProductTile.vue')['default']
    Quiz: typeof import('./components/Quiz.vue')['default']
    RadarChart: typeof import('./components/SubjectRadarChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    StudentBenefits: typeof import('./components/StudentBenefits.vue')['default']
    SubjectRadarChart: typeof import('./components/SubjectRadarChart.vue')['default']
    TopNavBar: typeof import('./components/TopNavBar.vue')['default']
    UserAvatar: typeof import('./components/UserAvatar.vue')['default']
  }
}
